server:
  port: 8111

spring:
  application:
    name: dieat-user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/menudb
    username: root
    password: mariadb

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: ture
      database: mysql
      properties:
        hibernate:
          '[format_sql]': true